/**
 * 실내 반려식물 지식 베이스.
 *
 * 서버(도구 핸들러)와 클라이언트 양쪽에서 쓸 수 있어야 하므로
 * 외부 의존성 없는 순수 데이터 모듈로 둔다 (config/SDK import 금지).
 *
 * toxicToPets 는 반려동물 안전 추천 필터의 입력이다 → 애매하면 위험 쪽(true)으로 두지 않고
 * ASPCA 기준 사실대로 적는다. 잘못된 false 는 사고로, 잘못된 true 는 추천 누락으로 이어진다.
 */

export interface PlantRecord {
  names: string[];
  displayName: string;
  scientificName: string;
  wateringDays: string;
  tempRange: string;
  humidity: string;
  light: 'direct_sun' | 'bright_indirect' | 'low_light';
  lightLabel: string;
  fertilizer: string;
  commonPests: string[];
  toxicToPets: boolean;
  toxicityNote: string;
  difficulty: 'beginner' | 'intermediate' | 'expert';
  traits: Array<'air_purifying' | 'flowering' | 'edible' | 'aesthetic' | 'low_maintenance'>;
  note: string;
}

// 빛 조건 문구는 세 등급으로 통일한다 — 종마다 다른 표현을 쓰면 UI 비교가 어려워진다.
const DIRECT = '직사광 — 하루 4시간 이상 햇빛이 드는 남향 창가';
const BRIGHT = '밝은 간접광 — 레이스 커튼을 친 창가';
const LOW = '반음지 — 창에서 떨어진 실내광에서도 버팀';

/** 반려동물 안전 종에 공통으로 붙는 문구 (그래도 과식은 배탈을 부른다) */
const SAFE_NOTE = '알려진 독성은 없어요. 다만 많이 씹어 먹으면 배탈이 날 수 있어요.';

export const PLANTS: PlantRecord[] = [
  {
    names: ['몬스테라', '몬스테라 델리시오사', '몬스테라 알보', 'monstera', 'monstera deliciosa'],
    displayName: '몬스테라',
    scientificName: 'Monstera deliciosa',
    wateringDays: '7-10일 (겉흙 2-3cm 마른 후)',
    tempRange: '18-27°C (13°C 이하 냉해)',
    humidity: '60% 이상',
    light: 'bright_indirect',
    lightLabel: BRIGHT,
    fertilizer: '봄~가을 월 1회 액체비료, 겨울 중단',
    commonPests: ['깍지벌레', '응애', '총채벌레'],
    toxicToPets: true,
    toxicityNote: '잎·줄기에 옥살산칼슘이 있어 씹으면 입안이 붓고 침을 많이 흘려요. 화분을 높은 곳에 두세요.',
    difficulty: 'beginner',
    traits: ['air_purifying', 'aesthetic'],
    note: '잎의 구멍(천공)은 빛이 충분하고 잎이 성숙할 때 생겨요. 지지대를 세워 위로 올리면 잎이 훨씬 커집니다.',
  },
  {
    names: ['스투키', '산세베리아 스투키', 'stucky', 'dracaena stuckyi'],
    displayName: '스투키',
    scientificName: 'Dracaena stuckyi (구 Sansevieria stuckyi)',
    wateringDays: '3-4주 (흙이 속까지 마른 후)',
    tempRange: '16-30°C',
    humidity: '30-50% (건조에 매우 강함)',
    light: 'low_light',
    lightLabel: LOW,
    fertilizer: '봄·여름 2-3개월에 1회, 권장량의 절반',
    commonPests: ['깍지벌레', '뿌리파리'],
    toxicToPets: true,
    toxicityNote: '사포닌이 있어 반려동물이 먹으면 구토·설사를 해요.',
    difficulty: 'beginner',
    traits: ['air_purifying', 'low_maintenance'],
    note: '죽는 원인은 거의 100% 과습이에요. 물을 줄까 말까 고민되면 일주일 더 기다리는 쪽이 안전합니다.',
  },
  {
    names: ['산세베리아', '산세', '스네이크플랜트', 'sansevieria', 'snake plant'],
    displayName: '산세베리아',
    scientificName: 'Dracaena trifasciata',
    wateringDays: '2-3주 (겨울엔 4-6주)',
    tempRange: '15-30°C',
    humidity: '30-50%',
    light: 'low_light',
    lightLabel: LOW,
    fertilizer: '봄~여름 2개월 1회 묽은 액체비료',
    commonPests: ['깍지벌레', '응애'],
    toxicToPets: true,
    toxicityNote: '사포닌 성분으로 구토·설사·식욕부진을 일으켜요. 고양이가 잎을 물어뜯기 쉬운 위치는 피하세요.',
    difficulty: 'beginner',
    traits: ['air_purifying', 'low_maintenance'],
    note: '밤에도 산소를 내보내 침실에 두기 좋아요. 잎이 물러지면 이미 뿌리가 상한 신호입니다.',
  },
  {
    names: ['포토스', '스킨답서스', '골든포토스', 'pothos', 'golden pothos', 'epipremnum aureum'],
    displayName: '포토스(스킨답서스)',
    scientificName: 'Epipremnum aureum',
    wateringDays: '7-10일 (잎이 살짝 처질 때)',
    tempRange: '18-30°C',
    humidity: '40-60%',
    light: 'low_light',
    lightLabel: LOW,
    fertilizer: '봄~가을 월 1회, 수경재배 시 영양제 소량',
    commonPests: ['깍지벌레', '뿌리파리'],
    toxicToPets: true,
    toxicityNote: '옥살산칼슘 때문에 입·목이 부어 침을 흘리고 삼키기 힘들어져요. 늘어뜨리면 고양이가 물기 쉬워 주의.',
    difficulty: 'beginner',
    traits: ['air_purifying', 'low_maintenance'],
    note: '줄기를 물컵에 꽂아두면 2주쯤 뒤 뿌리가 나요. 초보자 첫 식물로 가장 추천합니다.',
  },
  {
    names: ['고무나무', '인도고무나무', '흑고무나무', 'rubber plant', 'ficus elastica'],
    displayName: '고무나무',
    scientificName: 'Ficus elastica',
    wateringDays: '10-14일 (겉흙 마른 후 흠뻑)',
    tempRange: '16-27°C',
    humidity: '40-60%',
    light: 'bright_indirect',
    lightLabel: BRIGHT,
    fertilizer: '봄~가을 월 1회 액체비료',
    commonPests: ['깍지벌레', '응애', '총채벌레'],
    toxicToPets: true,
    toxicityNote: '자를 때 나오는 흰 유액이 입안과 피부를 자극해요. 반려동물이 씹으면 구토를 할 수 있어요.',
    difficulty: 'beginner',
    traits: ['air_purifying', 'aesthetic'],
    note: '한 방향으로만 빛을 받으면 기울어져요. 물 줄 때마다 화분을 조금씩 돌려주세요.',
  },
  {
    names: ['아레카야자', '아레카', 'areca palm', 'dypsis lutescens'],
    displayName: '아레카야자',
    scientificName: 'Dypsis lutescens',
    wateringDays: '5-7일 (겉흙이 마르면 바로)',
    tempRange: '18-27°C',
    humidity: '50-70%',
    light: 'bright_indirect',
    lightLabel: BRIGHT,
    fertilizer: '봄~가을 월 1회, 잎끝 마름 예방으로 묽게',
    commonPests: ['응애', '깍지벌레', '총채벌레'],
    toxicToPets: false,
    toxicityNote: '반려동물에게 안전한 식물이에요. 개·고양이가 있는 집에 마음 놓고 둘 수 있어요.',
    difficulty: 'intermediate',
    traits: ['air_purifying'],
    note: '증산량이 커서 천연 가습기 역할을 해요. 건조하면 잎끝이 갈색으로 타니 분무를 자주 해주세요.',
  },
  {
    names: ['스파티필름', '스파티필럼', '스파트필름', 'peace lily', 'spathiphyllum'],
    displayName: '스파티필름',
    scientificName: 'Spathiphyllum wallisii',
    wateringDays: '5-7일 (잎이 처지기 직전)',
    tempRange: '18-27°C',
    humidity: '50-70%',
    light: 'low_light',
    lightLabel: LOW,
    fertilizer: '봄~가을 월 1회, 꽃 보려면 인산 비율 높은 비료',
    commonPests: ['깍지벌레', '진딧물', '뿌리파리'],
    toxicToPets: true,
    toxicityNote: '옥살산칼슘이 있어 입안이 부어 침을 흘리고 구토를 해요. 반려동물 있으면 손 닿지 않는 곳에.',
    difficulty: 'beginner',
    traits: ['air_purifying', 'flowering'],
    note: '목마르면 잎을 축 늘어뜨려 신호를 보내요. 그때 물을 주면 몇 시간 안에 다시 서니 초보자에게 친절합니다.',
  },
  {
    names: ['필로덴드론', '필로', '하트필로덴드론', 'philodendron'],
    displayName: '필로덴드론',
    scientificName: 'Philodendron hederaceum',
    wateringDays: '7-10일',
    tempRange: '18-28°C',
    humidity: '50-70%',
    light: 'bright_indirect',
    lightLabel: BRIGHT,
    fertilizer: '봄~가을 월 1-2회 묽은 액체비료',
    commonPests: ['깍지벌레', '응애', '뿌리파리'],
    toxicToPets: true,
    toxicityNote: '옥살산칼슘 결정 때문에 입·혀가 붓고 침 흘림, 구토가 생겨요. 덩굴이 바닥에 닿지 않게 걸어두세요.',
    difficulty: 'beginner',
    traits: ['air_purifying', 'aesthetic'],
    note: '포토스와 비슷하지만 잎끝이 더 뾰족하고 하트 모양이 선명해요. 순지르기하면 풍성해집니다.',
  },
  {
    names: ['칼라테아', '칼라데아', '공작잎', 'calathea', 'goeppertia'],
    displayName: '칼라테아',
    scientificName: 'Goeppertia makoyana (구 Calathea makoyana)',
    wateringDays: '4-6일 (겉흙이 마르기 전에)',
    tempRange: '18-26°C',
    humidity: '60-80% (필수)',
    light: 'bright_indirect',
    lightLabel: BRIGHT,
    fertilizer: '봄~가을 월 1회, 권장량의 절반 (염류에 민감)',
    commonPests: ['응애', '총채벌레'],
    toxicToPets: false,
    toxicityNote: SAFE_NOTE,
    difficulty: 'intermediate',
    traits: ['aesthetic'],
    note: '수돗물의 염소·석회에 예민해요. 하루 받아둔 물이나 정수를 쓰고, 습도가 낮으면 잎이 말려버립니다.',
  },
  {
    names: ['선인장', '기둥선인장', '비화옥', 'cactus', 'cacti'],
    displayName: '선인장',
    scientificName: 'Cactaceae spp.',
    wateringDays: '3-4주 (겨울엔 6-8주 또는 단수)',
    tempRange: '10-32°C (겨울 5°C 이상)',
    humidity: '30-40%',
    light: 'direct_sun',
    lightLabel: DIRECT,
    fertilizer: '봄~여름 1-2개월 1회 선인장용 비료',
    commonPests: ['깍지벌레', '뿌리깍지벌레'],
    toxicToPets: false,
    toxicityNote: '독성은 없지만 가시가 입과 발을 찔러 다칠 수 있어요. 반려동물 동선에서 떨어진 곳에 두세요.',
    difficulty: 'beginner',
    traits: ['low_maintenance', 'aesthetic'],
    note: '겨울에 차갑고 건조하게 관리하면 봄에 꽃이 잘 펴요. 물 주기보다 배수 잘 되는 흙이 더 중요합니다.',
  },
  {
    names: ['에케베리아', '에케', '다육이', '다육식물', 'echeveria'],
    displayName: '에케베리아(다육)',
    scientificName: 'Echeveria spp.',
    wateringDays: '2-3주 (아래 잎이 살짝 주름질 때)',
    tempRange: '10-28°C (일교차 크면 색이 예뻐짐)',
    humidity: '30-50%',
    light: 'direct_sun',
    lightLabel: DIRECT,
    fertilizer: '봄·가을 2개월 1회 소량 (여름 휴면기 금지)',
    commonPests: ['깍지벌레', '진딧물', '뿌리파리'],
    toxicToPets: false,
    toxicityNote: SAFE_NOTE,
    difficulty: 'beginner',
    traits: ['low_maintenance', 'aesthetic'],
    note: '웃자라면(줄기가 길어지면) 빛이 부족한 거예요. 떨어진 잎을 흙에 얹어두면 새 개체가 나옵니다.',
  },
  {
    names: ['알로에', '알로에베라', 'aloe', 'aloe vera'],
    displayName: '알로에',
    scientificName: 'Aloe vera',
    wateringDays: '2-3주 (겨울엔 4주 이상)',
    tempRange: '13-27°C',
    humidity: '30-50%',
    light: 'direct_sun',
    lightLabel: DIRECT,
    fertilizer: '봄~여름 2개월 1회 묽게',
    commonPests: ['깍지벌레', '진딧물'],
    toxicToPets: true,
    toxicityNote: '껍질의 알로인·사포닌이 개·고양이에게 구토와 설사를 일으켜요. 사람에게 먹는 부분(속 젤)과 다릅니다.',
    difficulty: 'beginner',
    traits: ['low_maintenance', 'edible'],
    note: '잎이 얇아지고 접히면 물 부족 신호예요. 반대로 물러서 투명해지면 과습이니 즉시 물을 끊으세요.',
  },
  {
    names: ['행운목', '드라세나 맛산게아나', 'corn plant', 'dracaena fragrans'],
    displayName: '행운목',
    scientificName: 'Dracaena fragrans',
    wateringDays: '10-14일',
    tempRange: '16-27°C',
    humidity: '40-60%',
    light: 'low_light',
    lightLabel: LOW,
    fertilizer: '봄~가을 월 1회 액체비료',
    commonPests: ['깍지벌레', '응애', '총채벌레'],
    toxicToPets: true,
    toxicityNote: '사포닌 때문에 구토·침 흘림이 생기고 고양이는 동공이 커질 수 있어요.',
    difficulty: 'beginner',
    traits: ['air_purifying', 'low_maintenance'],
    note: '불소·염소에 민감해서 잎끝이 갈색으로 타요. 받아둔 물을 쓰고 통에 담긴 물은 갈아주세요.',
  },
  {
    names: ['테이블야자', '테이블 야자', 'parlor palm', 'chamaedorea elegans'],
    displayName: '테이블야자',
    scientificName: 'Chamaedorea elegans',
    wateringDays: '7-10일',
    tempRange: '16-26°C',
    humidity: '50-70%',
    light: 'low_light',
    lightLabel: LOW,
    fertilizer: '봄~가을 2개월 1회 묽게 (비료 과다에 약함)',
    commonPests: ['응애', '깍지벌레'],
    toxicToPets: false,
    toxicityNote: '반려동물에게 안전해요. 고양이가 잎을 씹어도 독성 걱정은 없습니다.',
    difficulty: 'beginner',
    traits: ['air_purifying', 'low_maintenance'],
    note: '어두운 방과 좁은 화분을 잘 견뎌 책상 위에 두기 좋아요. 분갈이를 자주 하지 않아도 됩니다.',
  },
  {
    names: ['금전수', '돈나무', '자미오쿨카스', 'zz plant', 'zamioculcas'],
    displayName: '금전수',
    scientificName: 'Zamioculcas zamiifolia',
    wateringDays: '3-4주 (겨울 6주)',
    tempRange: '15-30°C',
    humidity: '30-50%',
    light: 'low_light',
    lightLabel: LOW,
    fertilizer: '봄~여름 2-3개월 1회',
    commonPests: ['깍지벌레', '뿌리파리'],
    toxicToPets: true,
    toxicityNote: '옥살산칼슘이 있어 씹으면 입안이 아프고 구토를 해요. 수액이 피부에도 자극이 됩니다.',
    difficulty: 'beginner',
    traits: ['air_purifying', 'low_maintenance'],
    note: '땅속 알뿌리에 물을 저장해서 한 달 잊어도 살아요. 출장·여행이 많은 분께 가장 잘 맞습니다.',
  },
  {
    names: ['율마', '골드크레스트', 'wilma', 'monterey cypress'],
    displayName: '율마',
    scientificName: "Cupressus macrocarpa 'Goldcrest'",
    wateringDays: '3-5일 (절대 마르지 않게)',
    tempRange: '10-24°C (더위에 약함)',
    humidity: '50-70%',
    light: 'direct_sun',
    lightLabel: DIRECT,
    fertilizer: '봄·가을 월 1회 묽은 액체비료',
    commonPests: ['응애', '깍지벌레'],
    toxicToPets: true,
    toxicityNote: '침엽의 정유 성분이 개·고양이에게 위장 자극과 구토를 일으킬 수 있어요.',
    difficulty: 'intermediate',
    traits: ['aesthetic'],
    note: '한 번 마르면 갈색이 된 부분은 다시 살아나지 않아요. 통풍과 물 관리가 전부인 식물입니다.',
  },
  {
    names: ['로즈마리', 'rosemary', 'salvia rosmarinus'],
    displayName: '로즈마리',
    scientificName: 'Salvia rosmarinus (구 Rosmarinus officinalis)',
    wateringDays: '5-7일 (겉흙이 바싹 마른 후)',
    tempRange: '10-27°C',
    humidity: '40-50% (통풍 중요)',
    light: 'direct_sun',
    lightLabel: DIRECT,
    fertilizer: '봄·가을 2개월 1회 소량',
    commonPests: ['응애', '흰가루병', '진딧물'],
    toxicToPets: false,
    toxicityNote: '개·고양이에게 안전한 허브예요. 요리에 쓰는 그 로즈마리와 같습니다.',
    difficulty: 'intermediate',
    traits: ['edible', 'low_maintenance'],
    note: '과습과 통풍 부족이 최대 적이에요. 실내에서는 창문을 자주 열고 잎을 자주 수확해 순환시켜 주세요.',
  },
  {
    names: ['바질', 'basil', 'ocimum basilicum'],
    displayName: '바질',
    scientificName: 'Ocimum basilicum',
    wateringDays: '1-2일 (겉흙이 마르면 바로)',
    tempRange: '18-30°C (10°C 이하 냉해)',
    humidity: '50-60%',
    light: 'direct_sun',
    lightLabel: DIRECT,
    fertilizer: '수확기에는 2주 1회 묽은 액체비료',
    commonPests: ['진딧물', '온실가루이', '민달팽이'],
    toxicToPets: false,
    toxicityNote: '반려동물에게 안전해요. 사람도 그대로 먹을 수 있습니다.',
    difficulty: 'beginner',
    traits: ['edible'],
    note: '꽃대가 올라오면 잎이 질겨져요. 꽃봉오리는 바로 따고 윗부분을 잘라 수확하면 계속 새 잎이 납니다.',
  },
  {
    names: ['라벤더', 'lavender', 'lavandula'],
    displayName: '라벤더',
    scientificName: 'Lavandula angustifolia',
    wateringDays: '7-10일 (흙이 완전히 마른 후)',
    tempRange: '5-25°C (여름 고온다습에 약함)',
    humidity: '40% 이하 (건조하게)',
    light: 'direct_sun',
    lightLabel: DIRECT,
    fertilizer: '봄에 1회만, 비료가 많으면 향이 약해짐',
    commonPests: ['진딧물', '응애', '뿌리썩음병'],
    toxicToPets: true,
    toxicityNote: '리날룰·리날릴아세테이트가 개·고양이에게 구토와 무기력을 일으켜요. 정유는 특히 위험합니다.',
    difficulty: 'intermediate',
    traits: ['flowering', 'aesthetic'],
    note: '한국 장마철에 가장 많이 죽어요. 자갈을 섞은 배수 좋은 흙에 심고 비를 직접 맞히지 마세요.',
  },
  {
    names: ['아이비', '헤데라', '무늬아이비', 'ivy', 'english ivy', 'hedera helix'],
    displayName: '아이비',
    scientificName: 'Hedera helix',
    wateringDays: '5-7일',
    tempRange: '10-24°C',
    humidity: '50-70%',
    light: 'bright_indirect',
    lightLabel: BRIGHT,
    fertilizer: '봄~가을 월 1회 액체비료',
    commonPests: ['응애', '깍지벌레', '온실가루이'],
    toxicToPets: true,
    toxicityNote: '헤데린 사포닌이 있어 구토·설사·과도한 침 흘림을 일으키고 수액은 피부염을 유발해요.',
    difficulty: 'beginner',
    traits: ['air_purifying'],
    note: '건조하면 응애가 순식간에 번져요. 잎 뒷면에 물을 세게 뿌려 씻어주는 것이 가장 좋은 예방입니다.',
  },
  {
    names: ['홍콩야자', '쉐플레라', '쉐프렐라', 'schefflera', 'umbrella plant'],
    displayName: '홍콩야자',
    scientificName: 'Schefflera arboricola',
    wateringDays: '7-10일',
    tempRange: '16-27°C',
    humidity: '40-60%',
    light: 'bright_indirect',
    lightLabel: BRIGHT,
    fertilizer: '봄~가을 월 1회',
    commonPests: ['깍지벌레', '응애', '진딧물'],
    toxicToPets: true,
    toxicityNote: '옥살산칼슘 때문에 입안이 붓고 침을 흘려요. 잎이 낮게 퍼져 반려동물이 닿기 쉬우니 주의하세요.',
    difficulty: 'beginner',
    traits: ['air_purifying', 'low_maintenance'],
    note: '웃자라면 원하는 높이에서 잘라주세요. 자른 자리 아래에서 가지가 여러 개 나와 풍성해집니다.',
  },
  {
    names: ['벤자민고무나무', '벤자민', '벤자민 고무나무', 'ficus benjamina', 'weeping fig'],
    displayName: '벤자민고무나무',
    scientificName: 'Ficus benjamina',
    wateringDays: '7-10일',
    tempRange: '16-27°C',
    humidity: '50-60%',
    light: 'bright_indirect',
    lightLabel: BRIGHT,
    fertilizer: '봄~가을 월 1회',
    commonPests: ['깍지벌레', '응애', '온실가루이'],
    toxicToPets: true,
    toxicityNote: '흰 유액이 입안과 위를 자극해 구토·설사를 일으켜요.',
    difficulty: 'intermediate',
    traits: ['air_purifying'],
    note: '자리를 옮기면 스트레스로 잎을 우수수 떨어뜨려요. 마음에 드는 자리를 정하면 그대로 두는 게 좋습니다.',
  },
  {
    names: ['떡갈고무나무', '피델리프', 'fiddle leaf fig', 'ficus lyrata'],
    displayName: '떡갈고무나무',
    scientificName: 'Ficus lyrata',
    wateringDays: '10-14일 (겉흙 3cm 마른 후)',
    tempRange: '18-27°C',
    humidity: '50-65%',
    light: 'bright_indirect',
    lightLabel: BRIGHT,
    fertilizer: '봄~가을 월 1회 질소 위주',
    commonPests: ['깍지벌레', '응애', '총채벌레'],
    toxicToPets: true,
    toxicityNote: '유액에 자극 성분이 있어 씹으면 입안이 아프고 구토를 해요.',
    difficulty: 'intermediate',
    traits: ['aesthetic'],
    note: '큰 잎에 먼지가 잘 앉아요. 한 달에 한 번 젖은 천으로 닦아주면 광합성이 눈에 띄게 좋아집니다.',
  },
  {
    names: ['뱅갈고무나무', '벵갈고무나무', 'ficus benghalensis', 'banyan fig'],
    displayName: '뱅갈고무나무',
    scientificName: 'Ficus benghalensis',
    wateringDays: '10-14일',
    tempRange: '18-28°C',
    humidity: '45-60%',
    light: 'bright_indirect',
    lightLabel: BRIGHT,
    fertilizer: '봄~가을 월 1회',
    commonPests: ['깍지벌레', '응애'],
    toxicToPets: true,
    toxicityNote: '피쿠스 계열 공통으로 유액이 위장을 자극해 구토·설사를 일으켜요.',
    difficulty: 'beginner',
    traits: ['air_purifying', 'aesthetic'],
    note: '고무나무 중에서도 튼튼한 편이에요. 잎맥이 하얗게 도드라지는 게 특징이고 가지치기를 잘 견딥니다.',
  },
  {
    names: ['드라세나', '드라세나 마지나타', '마지나타', 'dracaena marginata', 'dragon tree'],
    displayName: '드라세나 마지나타',
    scientificName: 'Dracaena marginata',
    wateringDays: '10-14일',
    tempRange: '16-27°C',
    humidity: '40-60%',
    light: 'bright_indirect',
    lightLabel: BRIGHT,
    fertilizer: '봄~가을 2개월 1회',
    commonPests: ['응애', '깍지벌레', '총채벌레'],
    toxicToPets: true,
    toxicityNote: '사포닌 때문에 구토(때로 혈액 섞임)와 침 흘림이 생기고, 고양이는 동공이 확장돼요.',
    difficulty: 'beginner',
    traits: ['air_purifying', 'low_maintenance'],
    note: '잎끝 갈변은 대부분 수돗물의 불소 때문이에요. 받아둔 물을 쓰면 눈에 띄게 나아집니다.',
  },
  {
    names: ['개운죽', '행운죽', 'lucky bamboo', 'dracaena sanderiana'],
    displayName: '개운죽',
    scientificName: 'Dracaena sanderiana',
    wateringDays: '수경 시 주 1회 물 갈이 (흙 재배는 7일)',
    tempRange: '16-30°C',
    humidity: '40-60%',
    light: 'low_light',
    lightLabel: LOW,
    fertilizer: '2개월 1회 수경용 영양제 몇 방울',
    commonPests: ['깍지벌레', '조류(물때)'],
    toxicToPets: true,
    toxicityNote: '드라세나 계열 사포닌으로 구토·설사를 유발해요. 대나무가 아니라 드라세나입니다.',
    difficulty: 'beginner',
    traits: ['air_purifying', 'low_maintenance'],
    note: '수돗물 염소에 잎끝이 타요. 하루 받아둔 물로 갈고, 통 안쪽 물때는 그때그때 닦아주세요.',
  },
  {
    names: ['디펜바키아', 'dieffenbachia', 'dumb cane'],
    displayName: '디펜바키아',
    scientificName: 'Dieffenbachia seguine',
    wateringDays: '7-10일',
    tempRange: '18-27°C',
    humidity: '50-70%',
    light: 'low_light',
    lightLabel: LOW,
    fertilizer: '봄~가을 월 1회',
    commonPests: ['응애', '깍지벌레', '총채벌레'],
    toxicToPets: true,
    toxicityNote: '독성이 강한 편이에요. 씹으면 입안이 심하게 부어 삼키기 어려워지고 호흡이 힘들 수 있어요. 아이·반려동물 있는 집은 권하지 않아요.',
    difficulty: 'beginner',
    traits: ['air_purifying'],
    note: '잎무늬가 화려하지만 독성이 세니 자를 때 장갑을 끼고 수액이 피부에 닿지 않게 하세요.',
  },
  {
    names: ['안스리움', '안시리움', '홍학꽃', 'anthurium', 'flamingo flower'],
    displayName: '안스리움',
    scientificName: 'Anthurium andraeanum',
    wateringDays: '5-7일',
    tempRange: '18-28°C',
    humidity: '60-80%',
    light: 'bright_indirect',
    lightLabel: BRIGHT,
    fertilizer: '봄~가을 월 2회 묽은 인산 위주 비료',
    commonPests: ['깍지벌레', '총채벌레', '진딧물'],
    toxicToPets: true,
    toxicityNote: '옥살산칼슘으로 입·목이 붓고 침을 흘려요. 붉은 부분도 꽃이 아니라 잎이라 똑같이 위험합니다.',
    difficulty: 'intermediate',
    traits: ['flowering', 'aesthetic'],
    note: '붉은 하트는 꽃이 아니라 불염포예요. 습도가 높고 빛이 밝으면 1년 내내 새 불염포가 올라옵니다.',
  },
  {
    names: ['아글라오네마', '아글라오네마 실버퀸', 'aglaonema', 'chinese evergreen'],
    displayName: '아글라오네마',
    scientificName: 'Aglaonema commutatum',
    wateringDays: '7-12일',
    tempRange: '18-28°C',
    humidity: '50-70%',
    light: 'low_light',
    lightLabel: LOW,
    fertilizer: '봄~가을 2개월 1회',
    commonPests: ['깍지벌레', '응애', '뿌리파리'],
    toxicToPets: true,
    toxicityNote: '옥살산칼슘 때문에 구토와 입안 통증이 생겨요.',
    difficulty: 'beginner',
    traits: ['air_purifying', 'low_maintenance'],
    note: '어두운 곳에서도 무늬가 잘 유지돼 사무실에 적합해요. 다만 15°C 이하 냉기에는 잎이 검게 죽습니다.',
  },
  {
    names: ['싱고니움', 'syngonium', 'arrowhead plant'],
    displayName: '싱고니움',
    scientificName: 'Syngonium podophyllum',
    wateringDays: '5-8일',
    tempRange: '18-28°C',
    humidity: '55-75%',
    light: 'bright_indirect',
    lightLabel: BRIGHT,
    fertilizer: '봄~가을 월 1회',
    commonPests: ['응애', '깍지벌레'],
    toxicToPets: true,
    toxicityNote: '옥살산칼슘으로 입안 자극·구토를 일으켜요.',
    difficulty: 'beginner',
    traits: ['air_purifying'],
    note: '어릴 때는 화살촉 모양 잎이고 자라면서 덩굴이 돼요. 잘라서 물꽂이하면 뿌리가 아주 잘 납니다.',
  },
  {
    names: ['알로카시아', '거북알로카시아', 'alocasia', 'elephant ear'],
    displayName: '알로카시아',
    scientificName: 'Alocasia amazonica',
    wateringDays: '5-7일 (겨울 휴면 시 크게 줄임)',
    tempRange: '18-27°C',
    humidity: '60-80%',
    light: 'bright_indirect',
    lightLabel: BRIGHT,
    fertilizer: '봄~가을 월 1-2회 묽게',
    commonPests: ['응애', '총채벌레', '깍지벌레'],
    toxicToPets: true,
    toxicityNote: '옥살산칼슘 농도가 높아 입·목이 심하게 붓고 삼키기 어려워져요. 반려동물 있으면 피하세요.',
    difficulty: 'expert',
    traits: ['aesthetic'],
    note: '겨울에 잎을 모두 떨구고 알뿌리로 쉬어요. 죽은 줄 알고 버리지 말고 물을 줄여 봄까지 기다리세요.',
  },
  {
    names: ['셀렘', '셀로움', 'philodendron selloum', 'thaumatophyllum'],
    displayName: '셀렘',
    scientificName: 'Thaumatophyllum bipinnatifidum',
    wateringDays: '7-10일',
    tempRange: '18-28°C',
    humidity: '50-70%',
    light: 'bright_indirect',
    lightLabel: BRIGHT,
    fertilizer: '봄~가을 월 1회',
    commonPests: ['깍지벌레', '응애'],
    toxicToPets: true,
    toxicityNote: '필로덴드론 계열 옥살산칼슘으로 입안 통증과 구토가 생겨요.',
    difficulty: 'beginner',
    traits: ['air_purifying', 'aesthetic'],
    note: '잎이 옆으로 크게 벌어져 공간을 많이 차지해요. 넓은 거실 코너에 두면 존재감이 확실합니다.',
  },
  {
    names: ['크로톤', 'croton', 'codiaeum'],
    displayName: '크로톤',
    scientificName: 'Codiaeum variegatum',
    wateringDays: '5-7일',
    tempRange: '18-28°C (15°C 이하 잎 떨굼)',
    humidity: '50-70%',
    light: 'direct_sun',
    lightLabel: DIRECT,
    fertilizer: '봄~가을 월 1회',
    commonPests: ['응애', '깍지벌레', '온실가루이'],
    toxicToPets: true,
    toxicityNote: '유액에 자극 성분이 있어 구토·설사를 일으키고 피부에도 염증을 만들어요.',
    difficulty: 'intermediate',
    traits: ['aesthetic'],
    note: '빨강·노랑 잎색은 빛이 강할 때만 나와요. 어두우면 초록으로 돌아가고 잎도 떨어집니다.',
  },
  {
    names: ['관음죽', 'lady palm', 'rhapis excelsa'],
    displayName: '관음죽',
    scientificName: 'Rhapis excelsa',
    wateringDays: '7-10일',
    tempRange: '15-27°C',
    humidity: '40-60%',
    light: 'low_light',
    lightLabel: LOW,
    fertilizer: '봄~가을 2개월 1회',
    commonPests: ['응애', '깍지벌레'],
    toxicToPets: false,
    toxicityNote: '반려동물에게 안전한 야자예요. 실내 대형 화분 중 가장 마음 편한 선택입니다.',
    difficulty: 'beginner',
    traits: ['air_purifying', 'low_maintenance'],
    note: '느리게 자라지만 어둡고 건조한 실내를 잘 견뎌요. 아파트 현관·복도에도 잘 적응합니다.',
  },
  {
    names: ['켄챠야자', '켄티아야자', 'kentia palm', 'howea forsteriana'],
    displayName: '켄챠야자',
    scientificName: 'Howea forsteriana',
    wateringDays: '7-10일',
    tempRange: '16-27°C',
    humidity: '50-60%',
    light: 'bright_indirect',
    lightLabel: BRIGHT,
    fertilizer: '봄~가을 2개월 1회 묽게',
    commonPests: ['응애', '깍지벌레'],
    toxicToPets: false,
    toxicityNote: '반려동물에게 안전해요.',
    difficulty: 'beginner',
    traits: ['air_purifying', 'aesthetic'],
    note: '뿌리를 건드리면 크게 스트레스를 받아요. 분갈이는 뿌리가 화분을 꽉 채운 뒤에만 하세요.',
  },
  {
    names: ['파키라', '파키라머니트리', 'pachira', 'money tree'],
    displayName: '파키라',
    scientificName: 'Pachira aquatica',
    wateringDays: '10-14일',
    tempRange: '16-28°C',
    humidity: '40-60%',
    light: 'bright_indirect',
    lightLabel: BRIGHT,
    fertilizer: '봄~가을 2개월 1회',
    commonPests: ['깍지벌레', '응애', '뿌리파리'],
    toxicToPets: false,
    toxicityNote: '알려진 독성이 없어 반려동물 있는 집에 두기 좋아요.',
    difficulty: 'beginner',
    traits: ['low_maintenance', 'aesthetic'],
    note: '줄기에 물을 저장해 물을 자주 안 줘도 돼요. 오히려 자주 주면 뿌리가 썩고 잎이 노랗게 떨어집니다.',
  },
  {
    names: ['여인초', '스트렐리치아 니콜라이', 'strelitzia nicolai', 'white bird of paradise'],
    displayName: '여인초',
    scientificName: 'Strelitzia nicolai',
    wateringDays: '7-10일',
    tempRange: '18-28°C',
    humidity: '50-70%',
    light: 'direct_sun',
    lightLabel: DIRECT,
    fertilizer: '봄~가을 월 1회',
    commonPests: ['응애', '깍지벌레', '총채벌레'],
    toxicToPets: true,
    toxicityNote: '씨앗과 잎에 독성 성분이 있어 구토·졸음·소화기 이상을 일으켜요.',
    difficulty: 'intermediate',
    traits: ['aesthetic'],
    note: '큰 잎이 자연스럽게 갈라지는 건 병이 아니에요. 빛이 강할수록 잎이 크고 곧게 자랍니다.',
  },
  {
    names: ['극락조', '극락조화', 'bird of paradise', 'strelitzia reginae'],
    displayName: '극락조',
    scientificName: 'Strelitzia reginae',
    wateringDays: '7-10일',
    tempRange: '18-28°C',
    humidity: '50-60%',
    light: 'direct_sun',
    lightLabel: DIRECT,
    fertilizer: '봄~가을 월 1-2회, 개화기엔 인산 추가',
    commonPests: ['깍지벌레', '응애'],
    toxicToPets: true,
    toxicityNote: '꽃과 씨앗에 독성이 있어 반려동물이 먹으면 구토와 무기력이 나타나요.',
    difficulty: 'intermediate',
    traits: ['flowering', 'aesthetic'],
    note: '실내에서 꽃을 보려면 강한 직사광과 뿌리가 꽉 찬 화분, 그리고 4-5년의 시간이 필요해요.',
  },
  {
    names: ['유칼립투스', 'eucalyptus'],
    displayName: '유칼립투스',
    scientificName: 'Eucalyptus gunnii',
    wateringDays: '3-5일 (마르면 바로 시듦)',
    tempRange: '10-25°C',
    humidity: '40-60% (통풍 필수)',
    light: 'direct_sun',
    lightLabel: DIRECT,
    fertilizer: '봄·가을 2개월 1회 소량',
    commonPests: ['응애', '깍지벌레', '흰가루병'],
    toxicToPets: true,
    toxicityNote: '유칼립톨 성분이 개·고양이에게 침 흘림, 구토, 무기력을 일으켜요. 말린 가지도 위험합니다.',
    difficulty: 'expert',
    traits: ['aesthetic'],
    note: '실내에서 가장 자주 실패하는 식물이에요. 하루 대부분 직사광이 드는 베란다가 아니면 버티기 어렵습니다.',
  },
  {
    names: ['민트', '애플민트', '페퍼민트', 'mint', 'peppermint', 'mentha'],
    displayName: '민트',
    scientificName: 'Mentha spp.',
    wateringDays: '2-3일 (흙이 촉촉하게)',
    tempRange: '15-28°C',
    humidity: '50-70%',
    light: 'bright_indirect',
    lightLabel: BRIGHT,
    fertilizer: '수확기 2주 1회 묽은 액체비료',
    commonPests: ['진딧물', '응애', '녹병'],
    toxicToPets: true,
    toxicityNote: '많이 먹으면 개·고양이에게 구토·설사를 일으켜요. 정유(오일) 형태는 특히 위험합니다.',
    difficulty: 'beginner',
    traits: ['edible'],
    note: '뿌리가 무섭게 번져서 다른 식물과 같은 화분에 심으면 안 돼요. 반드시 단독 화분에 키우세요.',
  },
  {
    names: ['타임', '백리향', 'thyme', 'thymus'],
    displayName: '타임',
    scientificName: 'Thymus vulgaris',
    wateringDays: '5-7일 (건조하게)',
    tempRange: '10-27°C',
    humidity: '40-50%',
    light: 'direct_sun',
    lightLabel: DIRECT,
    fertilizer: '봄에 1회 소량 (많으면 향이 약해짐)',
    commonPests: ['응애', '진딧물'],
    toxicToPets: false,
    toxicityNote: '반려동물에게 안전한 허브예요.',
    difficulty: 'beginner',
    traits: ['edible', 'low_maintenance'],
    note: '허브 중에서도 건조에 강해요. 물을 적게 주고 볕을 많이 줄수록 향이 진해집니다.',
  },
  {
    names: ['아스파라거스', '아스파라거스 나누스', 'asparagus fern', 'asparagus setaceus'],
    displayName: '아스파라거스(관상용)',
    scientificName: 'Asparagus setaceus',
    wateringDays: '5-7일',
    tempRange: '15-26°C',
    humidity: '50-70%',
    light: 'bright_indirect',
    lightLabel: BRIGHT,
    fertilizer: '봄~가을 월 1회 묽게',
    commonPests: ['응애', '깍지벌레'],
    toxicToPets: true,
    toxicityNote: '사포게닌 때문에 열매를 먹으면 구토·설사, 잎에 반복 접촉하면 피부염이 생겨요.',
    difficulty: 'beginner',
    traits: ['aesthetic'],
    note: '고사리처럼 보이지만 실제로는 백합 친척이에요. 잎처럼 보이는 부분은 변형된 줄기입니다.',
  },
  {
    names: ['보스턴고사리', '고사리', 'boston fern', 'nephrolepis'],
    displayName: '보스턴고사리',
    scientificName: 'Nephrolepis exaltata',
    wateringDays: '2-4일 (항상 촉촉하게)',
    tempRange: '16-24°C',
    humidity: '60-80% (필수)',
    light: 'bright_indirect',
    lightLabel: BRIGHT,
    fertilizer: '봄~가을 월 1회 아주 묽게',
    commonPests: ['깍지벌레', '응애', '민달팽이'],
    toxicToPets: false,
    toxicityNote: '반려동물에게 안전해요. 고양이가 잎을 뜯어도 걱정 없습니다.',
    difficulty: 'intermediate',
    traits: ['air_purifying'],
    note: '가습 효과가 가장 큰 실내식물 중 하나예요. 대신 하루만 말라도 잎이 바스러지니 습도 관리가 핵심입니다.',
  },
  {
    names: ['박쥐란', '박쥐 란', 'staghorn fern', 'platycerium'],
    displayName: '박쥐란',
    scientificName: 'Platycerium bifurcatum',
    wateringDays: '주 1회 통째로 물에 담그기(침수 10분)',
    tempRange: '16-27°C',
    humidity: '60-80%',
    light: 'bright_indirect',
    lightLabel: BRIGHT,
    fertilizer: '봄~가을 2개월 1회 묽은 액체비료',
    commonPests: ['깍지벌레', '응애'],
    toxicToPets: false,
    toxicityNote: SAFE_NOTE,
    difficulty: 'intermediate',
    traits: ['aesthetic'],
    note: '갈색으로 판처럼 붙는 잎(영양엽)은 죽은 게 아니라 뿌리를 감싸는 기관이에요. 절대 떼지 마세요.',
  },
  {
    names: ['아디안텀', '공작고사리', 'maidenhair fern', 'adiantum'],
    displayName: '아디안텀',
    scientificName: 'Adiantum raddianum',
    wateringDays: '1-2일 (마르면 즉시 잎이 탄다)',
    tempRange: '16-24°C',
    humidity: '70% 이상',
    light: 'low_light',
    lightLabel: LOW,
    fertilizer: '봄~가을 월 1회 아주 묽게',
    commonPests: ['깍지벌레', '뿌리파리'],
    toxicToPets: false,
    toxicityNote: SAFE_NOTE,
    difficulty: 'expert',
    traits: ['aesthetic'],
    note: '습도에 가장 예민한 식물이에요. 욕실 창가처럼 늘 습한 곳이 아니면 유리 케이스 안에서 키우세요.',
  },
  {
    names: ['아스플레니움', '새둥지고사리', 'bird nest fern', 'asplenium nidus'],
    displayName: '아스플레니움',
    scientificName: 'Asplenium nidus',
    wateringDays: '4-6일 (중앙 순에는 물 붓지 않기)',
    tempRange: '18-27°C',
    humidity: '60-80%',
    light: 'low_light',
    lightLabel: LOW,
    fertilizer: '봄~가을 2개월 1회 묽게',
    commonPests: ['깍지벌레', '응애'],
    toxicToPets: false,
    toxicityNote: SAFE_NOTE,
    difficulty: 'beginner',
    traits: ['air_purifying'],
    note: '가운데 새순이 모인 곳에 물이 고이면 썩어요. 흙에만 물을 주고 잎에는 분무만 하세요.',
  },
  {
    names: ['틸란드시아', '수염틸란', '이오난사', 'tillandsia', 'air plant'],
    displayName: '틸란드시아',
    scientificName: 'Tillandsia ionantha',
    wateringDays: '주 1-2회 침수 20분 후 완전히 말리기',
    tempRange: '15-30°C',
    humidity: '50-70%',
    light: 'bright_indirect',
    lightLabel: BRIGHT,
    fertilizer: '월 1회 틸란드시아용 엽면시비',
    commonPests: ['깍지벌레'],
    toxicToPets: false,
    toxicityNote: SAFE_NOTE,
    difficulty: 'intermediate',
    traits: ['low_maintenance', 'aesthetic'],
    note: '흙 없이 공기 중 수분으로 살아요. 물에 담근 뒤 거꾸로 세워 4시간 안에 말려야 중심부가 썩지 않습니다.',
  },
  {
    names: ['립살리스', 'rhipsalis', 'mistletoe cactus'],
    displayName: '립살리스',
    scientificName: 'Rhipsalis baccifera',
    wateringDays: '10-14일',
    tempRange: '15-28°C',
    humidity: '50-70%',
    light: 'bright_indirect',
    lightLabel: BRIGHT,
    fertilizer: '봄~여름 2개월 1회 묽게',
    commonPests: ['깍지벌레', '뿌리파리'],
    toxicToPets: false,
    toxicityNote: SAFE_NOTE,
    difficulty: 'beginner',
    traits: ['low_maintenance', 'aesthetic'],
    note: '가시 없는 열대 선인장이라 직사광에 타요. 밝은 간접광에 걸어두면 줄기가 길게 늘어져 멋있습니다.',
  },
  {
    names: ['하월시아', '하워시아', '십이지권', 'haworthia', 'zebra plant'],
    displayName: '하월시아',
    scientificName: 'Haworthiopsis fasciata',
    wateringDays: '2-3주',
    tempRange: '13-28°C',
    humidity: '30-50%',
    light: 'bright_indirect',
    lightLabel: BRIGHT,
    fertilizer: '봄·가을 2개월 1회 소량',
    commonPests: ['뿌리깍지벌레', '뿌리파리'],
    toxicToPets: false,
    toxicityNote: SAFE_NOTE,
    difficulty: 'beginner',
    traits: ['low_maintenance', 'aesthetic'],
    note: '다육이지만 강한 직사광엔 잎이 붉게 타요. 밝은 그늘에서 오히려 투명한 창(窓)이 예쁘게 유지됩니다.',
  },
  {
    names: ['페페로미아', '페페', 'peperomia', 'baby rubber plant'],
    displayName: '페페로미아',
    scientificName: 'Peperomia obtusifolia',
    wateringDays: '10-14일',
    tempRange: '18-27°C',
    humidity: '40-60%',
    light: 'bright_indirect',
    lightLabel: BRIGHT,
    fertilizer: '봄~가을 2개월 1회 묽게',
    commonPests: ['깍지벌레', '뿌리파리'],
    toxicToPets: false,
    toxicityNote: '반려동물에게 안전한 식물로 알려져 있어요.',
    difficulty: 'beginner',
    traits: ['low_maintenance', 'aesthetic'],
    note: '두꺼운 잎에 물을 저장해요. 다육이처럼 생각하고 물을 아끼면 실패가 거의 없습니다.',
  },
  {
    names: ['호야', '하트호야', 'hoya', 'wax plant'],
    displayName: '호야',
    scientificName: 'Hoya carnosa',
    wateringDays: '10-14일',
    tempRange: '16-29°C',
    humidity: '50-70%',
    light: 'bright_indirect',
    lightLabel: BRIGHT,
    fertilizer: '봄~가을 월 1회, 개화기엔 인산 위주',
    commonPests: ['깍지벌레', '진딧물', '응애'],
    toxicToPets: false,
    toxicityNote: '독성은 없지만 흰 수액이 피부에 닿으면 가려울 수 있어요.',
    difficulty: 'beginner',
    traits: ['flowering', 'low_maintenance'],
    note: '꽃이 핀 자리(화경)는 자르지 마세요. 다음 해 같은 자리에서 다시 꽃이 올라옵니다.',
  },
  {
    names: ['마란타', '기도하는식물', 'maranta', 'prayer plant'],
    displayName: '마란타',
    scientificName: 'Maranta leuconeura',
    wateringDays: '4-6일',
    tempRange: '18-27°C',
    humidity: '60-80%',
    light: 'low_light',
    lightLabel: LOW,
    fertilizer: '봄~가을 월 1회 묽게',
    commonPests: ['응애', '깍지벌레'],
    toxicToPets: false,
    toxicityNote: '반려동물에게 안전해요.',
    difficulty: 'intermediate',
    traits: ['aesthetic'],
    note: '밤에 잎을 위로 접어 기도하는 모습이 돼요. 잎이 계속 접혀 있으면 물이나 습도가 부족한 신호입니다.',
  },
  {
    names: ['베고니아', 'begonia'],
    displayName: '베고니아',
    scientificName: 'Begonia spp.',
    wateringDays: '5-7일 (잎에 물 닿지 않게)',
    tempRange: '16-26°C',
    humidity: '50-70%',
    light: 'bright_indirect',
    lightLabel: BRIGHT,
    fertilizer: '봄~가을 2주 1회 묽은 액체비료',
    commonPests: ['흰가루병', '진딧물', '온실가루이'],
    toxicToPets: true,
    toxicityNote: '수용성 옥살산칼슘이 있어 입안이 아프고 구토를 해요. 특히 알뿌리 부분이 위험합니다.',
    difficulty: 'intermediate',
    traits: ['flowering', 'aesthetic'],
    note: '잎이 젖은 채로 밤을 넘기면 흰가루병이 와요. 아침에 흙에만 물을 주고 통풍을 시켜주세요.',
  },
  {
    names: ['제라늄', '제라니움', 'geranium', 'pelargonium'],
    displayName: '제라늄',
    scientificName: 'Pelargonium spp.',
    wateringDays: '5-7일 (겉흙 마른 후)',
    tempRange: '10-26°C',
    humidity: '40-60%',
    light: 'direct_sun',
    lightLabel: DIRECT,
    fertilizer: '개화기 2주 1회 인산 위주 비료',
    commonPests: ['온실가루이', '진딧물', '녹병'],
    toxicToPets: true,
    toxicityNote: '제라니올·리날룰 성분이 개·고양이에게 구토, 식욕부진, 피부염을 일으켜요.',
    difficulty: 'beginner',
    traits: ['flowering'],
    note: '시든 꽃대를 부지런히 따줘야 계속 피어요. 물을 적게 주고 볕을 많이 줄 때 꽃이 가장 많습니다.',
  },
  {
    names: ['아프리카바이올렛', '아프리칸바이올렛', 'african violet', 'saintpaulia'],
    displayName: '아프리카바이올렛',
    scientificName: 'Streptocarpus sect. Saintpaulia',
    wateringDays: '5-7일 (저면관수 권장)',
    tempRange: '18-24°C',
    humidity: '50-60%',
    light: 'bright_indirect',
    lightLabel: BRIGHT,
    fertilizer: '개화기 2주 1회 전용 비료',
    commonPests: ['총채벌레', '깍지벌레', '응애'],
    toxicToPets: false,
    toxicityNote: '반려동물에게 안전해요. 꽃이 있는 식물 중 드물게 안심할 수 있는 종입니다.',
    difficulty: 'intermediate',
    traits: ['flowering'],
    note: '털 있는 잎에 물이 닿으면 반점이 생겨요. 화분을 물받침에 20분 담그는 저면관수가 가장 안전합니다.',
  },
  {
    names: ['시클라멘', 'cyclamen'],
    displayName: '시클라멘',
    scientificName: 'Cyclamen persicum',
    wateringDays: '5-7일 (저면관수, 구근에 물 금지)',
    tempRange: '10-20°C (더위에 약함)',
    humidity: '50-60%',
    light: 'bright_indirect',
    lightLabel: BRIGHT,
    fertilizer: '개화기 2주 1회 묽은 액체비료',
    commonPests: ['총채벌레', '진딧물', '무름병'],
    toxicToPets: true,
    toxicityNote: '사포닌이 특히 알뿌리에 많아 구토·설사, 많이 먹으면 심장 이상까지 올 수 있어요.',
    difficulty: 'intermediate',
    traits: ['flowering'],
    note: '겨울에 꽃이 피고 여름엔 잎을 떨구고 쉬어요. 그때 물을 끊고 서늘한 그늘에 두면 가을에 다시 올라옵니다.',
  },
  {
    names: ['포인세티아', '크리스마스꽃', 'poinsettia', 'euphorbia pulcherrima'],
    displayName: '포인세티아',
    scientificName: 'Euphorbia pulcherrima',
    wateringDays: '5-7일',
    tempRange: '16-24°C (찬바람 절대 금지)',
    humidity: '50-60%',
    light: 'bright_indirect',
    lightLabel: BRIGHT,
    fertilizer: '개화기 이후 월 1회',
    commonPests: ['온실가루이', '깍지벌레', '뿌리파리'],
    toxicToPets: true,
    toxicityNote: '흰 유액이 입안과 위를 자극해 침 흘림·구토를 일으켜요. 치명적이지는 않지만 씹지 못하게 하세요.',
    difficulty: 'intermediate',
    traits: ['flowering'],
    note: '붉은 부분은 꽃이 아니라 잎이에요. 가을에 하루 14시간 완전한 암흑을 줘야 다시 붉게 물듭니다.',
  },
  {
    names: ['게발선인장', '크리스마스선인장', 'christmas cactus', 'schlumbergera'],
    displayName: '게발선인장',
    scientificName: 'Schlumbergera truncata',
    wateringDays: '10-14일 (개화기엔 7일)',
    tempRange: '15-24°C',
    humidity: '50-60%',
    light: 'bright_indirect',
    lightLabel: BRIGHT,
    fertilizer: '봄~여름 월 1회, 꽃눈 생기면 인산 위주',
    commonPests: ['깍지벌레', '뿌리파리'],
    toxicToPets: false,
    toxicityNote: '반려동물에게 안전해요. 겨울 꽃식물 중 가장 안심할 수 있는 선택입니다.',
    difficulty: 'beginner',
    traits: ['flowering', 'low_maintenance'],
    note: '가을에 서늘하고 밤이 긴 환경을 주면 꽃눈이 생겨요. 꽃봉오리가 생긴 뒤 자리를 옮기면 다 떨어집니다.',
  },
  {
    names: ['커피나무', '커피', 'coffee plant', 'coffea arabica'],
    displayName: '커피나무',
    scientificName: 'Coffea arabica',
    wateringDays: '5-7일',
    tempRange: '18-26°C',
    humidity: '55-70%',
    light: 'bright_indirect',
    lightLabel: BRIGHT,
    fertilizer: '봄~가을 월 1회 산성 토양용 비료',
    commonPests: ['깍지벌레', '응애', '총채벌레'],
    toxicToPets: true,
    toxicityNote: '잎과 열매의 카페인이 개·고양이에게 구토, 심박수 증가, 흥분 증상을 일으켜요.',
    difficulty: 'intermediate',
    traits: ['aesthetic'],
    note: '잎이 반짝이는 진한 초록이라 관엽으로도 좋아요. 열매까지 보려면 3-4년과 충분한 빛이 필요합니다.',
  },
  {
    names: ['올리브나무', '올리브', 'olive tree', 'olea europaea'],
    displayName: '올리브나무',
    scientificName: 'Olea europaea',
    wateringDays: '7-10일 (겉흙 완전히 마른 후)',
    tempRange: '5-30°C',
    humidity: '40-50% (건조 선호)',
    light: 'direct_sun',
    lightLabel: DIRECT,
    fertilizer: '봄·초여름 월 1회 질소 위주',
    commonPests: ['깍지벌레', '응애', '탄저병'],
    toxicToPets: false,
    toxicityNote: '반려동물에게 안전해요.',
    difficulty: 'intermediate',
    traits: ['edible', 'aesthetic'],
    note: '실내 조명만으로는 부족해요. 하루 6시간 직사광이 드는 베란다나 창가가 아니면 잎이 성기게 자랍니다.',
  },
  {
    names: ['접란', '나비란', 'spider plant', 'chlorophytum comosum'],
    displayName: '접란',
    scientificName: 'Chlorophytum comosum',
    wateringDays: '7-10일',
    tempRange: '13-27°C',
    humidity: '40-60%',
    light: 'bright_indirect',
    lightLabel: BRIGHT,
    fertilizer: '봄~가을 2개월 1회 묽게',
    commonPests: ['응애', '깍지벌레', '진딧물'],
    toxicToPets: false,
    toxicityNote: '독성은 없어요. 다만 고양이가 좋아해 자주 씹으면 배탈이 날 수 있어요.',
    difficulty: 'beginner',
    traits: ['air_purifying', 'low_maintenance'],
    note: '런너(줄기) 끝에 달린 새끼 포기를 잘라 심으면 바로 새 화분이 돼요. 나눠주기 좋은 식물입니다.',
  },
  {
    names: ['칼랑코에', '카랑코에', 'kalanchoe'],
    displayName: '칼랑코에',
    scientificName: 'Kalanchoe blossfeldiana',
    wateringDays: '10-14일',
    tempRange: '15-27°C',
    humidity: '40-50%',
    light: 'direct_sun',
    lightLabel: DIRECT,
    fertilizer: '개화기 전 월 1회 인산 위주',
    commonPests: ['진딧물', '깍지벌레', '뿌리파리'],
    toxicToPets: true,
    toxicityNote: '강심배당체가 있어 구토·설사, 많은 양은 심장 리듬을 흐트러뜨려요. 반려동물 있으면 피하세요.',
    difficulty: 'beginner',
    traits: ['flowering', 'low_maintenance'],
    note: '다육식물이라 물을 아껴야 해요. 꽃이 다 지면 꽃대를 잘라주면 몇 달 뒤 다시 피웁니다.',
  },
  {
    names: ['유포르비아', '백각기린', 'euphorbia trigona', 'african milk tree'],
    displayName: '유포르비아(백각기린)',
    scientificName: 'Euphorbia trigona',
    wateringDays: '2-3주',
    tempRange: '15-30°C',
    humidity: '30-50%',
    light: 'direct_sun',
    lightLabel: DIRECT,
    fertilizer: '봄~여름 2개월 1회 선인장용 비료',
    commonPests: ['깍지벌레', '응애'],
    toxicToPets: true,
    toxicityNote: '흰 유액이 강한 자극성이라 눈에 들어가면 위험하고 먹으면 구토를 해요. 손질할 때 장갑을 끼세요.',
    difficulty: 'beginner',
    traits: ['low_maintenance', 'aesthetic'],
    note: '선인장처럼 보이지만 대극과예요. 자른 자리에서 나오는 흰 즙은 물로 씻어내고 마를 때까지 두세요.',
  },
  {
    names: ['트리안', 'muehlenbeckia', 'wire vine'],
    displayName: '트리안',
    scientificName: 'Muehlenbeckia complexa',
    wateringDays: '3-5일 (마르면 바로 잎이 떨어짐)',
    tempRange: '10-25°C',
    humidity: '50-70%',
    light: 'bright_indirect',
    lightLabel: BRIGHT,
    fertilizer: '봄~가을 월 1회 묽게',
    commonPests: ['응애', '깍지벌레'],
    toxicToPets: false,
    toxicityNote: '보고된 독성은 없어요. 그래도 많이 먹으면 배탈이 날 수 있어요.',
    difficulty: 'intermediate',
    traits: ['aesthetic'],
    note: '작은 잎이 한 번 마르면 우수수 떨어져요. 흙 표면이 마르기 전에 주는 습관을 들이세요.',
  },
  {
    names: ['산호수', '백량금', '천냥금', 'ardisia', 'coral berry'],
    displayName: '산호수',
    scientificName: 'Ardisia pusilla',
    wateringDays: '4-6일',
    tempRange: '13-25°C',
    humidity: '50-70%',
    light: 'bright_indirect',
    lightLabel: BRIGHT,
    fertilizer: '봄~가을 2개월 1회',
    commonPests: ['깍지벌레', '응애'],
    toxicToPets: true,
    toxicityNote: '빨간 열매를 반려동물이 먹으면 구토·설사를 해요. 열매가 떨어지면 바로 치워주세요.',
    difficulty: 'beginner',
    traits: ['air_purifying', 'aesthetic'],
    note: '겨울에 빨간 열매가 오래 달려 있어요. 열매를 보려면 가을에 서늘하고 밝은 곳에 두세요.',
  },
  {
    names: ['립스틱', '에스키난서스', 'lipstick plant', 'aeschynanthus'],
    displayName: '립스틱',
    scientificName: 'Aeschynanthus radicans',
    wateringDays: '7-10일',
    tempRange: '18-27°C',
    humidity: '60-75%',
    light: 'bright_indirect',
    lightLabel: BRIGHT,
    fertilizer: '봄~가을 월 1-2회 인산 위주',
    commonPests: ['깍지벌레', '응애', '진딧물'],
    toxicToPets: false,
    toxicityNote: '반려동물에게 안전한 식물이에요.',
    difficulty: 'intermediate',
    traits: ['flowering', 'aesthetic'],
    note: '뿌리가 살짝 답답할 정도의 작은 화분에서 꽃이 더 잘 펴요. 분갈이를 서두르지 마세요.',
  },
  {
    names: ['배초향', '방아잎', '방아', 'agastache rugosa', 'korean mint'],
    displayName: '배초향',
    scientificName: 'Agastache rugosa',
    wateringDays: '5-7일 (겉흙 마른 후)',
    tempRange: '10-28°C',
    humidity: '40-60%',
    light: 'direct_sun',
    lightLabel: DIRECT,
    fertilizer: '봄~가을 월 1회 묽은 액체비료',
    commonPests: ['진딧물', '응애'],
    toxicToPets: false,
    toxicityNote: '반려동물에게 안전한 허브예요.',
    difficulty: 'beginner',
    traits: ['edible', 'flowering'],
    note: '방아잎이라 불리며 향이 강해 쌈·전에 많이 써요. 잎을 자주 따줘야 옆으로 풍성하게 자랍니다.',
  },
  {
    names: ['칼란디바', '칼란디바 칼랑코에', 'calandiva', 'kalanchoe calandiva'],
    displayName: '칼란디바',
    scientificName: "Kalanchoe blossfeldiana 'Calandiva'",
    wateringDays: '10-14일',
    tempRange: '15-27°C',
    humidity: '40-50%',
    light: 'direct_sun',
    lightLabel: DIRECT,
    fertilizer: '개화기 전 월 1회 인산 위주',
    commonPests: ['진딧물', '깍지벌레', '뿌리파리'],
    toxicToPets: true,
    toxicityNote: '강심배당체가 있어 구토·설사, 많은 양은 심장 리듬을 흐트러뜨려요. 반려동물 있으면 피하세요.',
    difficulty: 'beginner',
    traits: ['flowering', 'low_maintenance'],
    note: '칼랑코에의 겹꽃 품종이에요. 관리법은 칼랑코에와 같고, 꽃송이가 훨씬 풍성하고 오래갑니다.',
  },
  {
    names: ['일일초', '빈카', 'catharanthus roseus', 'madagascar periwinkle', 'vinca'],
    displayName: '일일초',
    scientificName: 'Catharanthus roseus',
    wateringDays: '5-7일 (겉흙 마른 후)',
    tempRange: '18-30°C (더위에 강함)',
    humidity: '40-60%',
    light: 'direct_sun',
    lightLabel: DIRECT,
    fertilizer: '개화기 월 1회 묽은 액체비료',
    commonPests: ['진딧물', '응애', '흰가루병'],
    toxicToPets: true,
    toxicityNote: '빈카알칼로이드 성분이 있어 개·고양이가 먹으면 구토·설사, 많이 먹으면 신경·혈액 이상까지 올 수 있어요.',
    difficulty: 'beginner',
    traits: ['flowering', 'low_maintenance'],
    note: '이름대로 매일 새 꽃이 피고 져요. 더위와 가뭄에 강해서 한여름 화단·베란다에서 특히 잘 자랍니다.',
  },
  {
    names: ['해바라기', 'sunflower', 'helianthus annuus'],
    displayName: '해바라기',
    scientificName: 'Helianthus annuus',
    wateringDays: '3-5일 (흙이 마르지 않게)',
    tempRange: '18-30°C',
    humidity: '40-60%',
    light: 'direct_sun',
    lightLabel: DIRECT,
    fertilizer: '생장기 2주 1회, 개화 전 인산·칼륨 위주',
    commonPests: ['진딧물', '민달팽이', '흰가루병'],
    toxicToPets: false,
    toxicityNote: '반려동물에게 안전해요. 씨앗도 소량이면 사람·동물 모두 먹을 수 있어요.',
    difficulty: 'beginner',
    traits: ['flowering', 'edible'],
    note: '하루 6시간 이상 직사광을 못 받으면 줄기가 가늘고 웃자라요. 화분이라면 뿌리가 넉넉한 큰 화분을 쓰세요.',
  },
  {
    names: ['봉선화', '봉숭아', 'impatiens balsamina', 'garden balsam'],
    displayName: '봉선화',
    scientificName: 'Impatiens balsamina',
    wateringDays: '3-5일 (흙이 촉촉하게)',
    tempRange: '18-28°C (더위·습도에 약간 민감)',
    humidity: '50-70%',
    light: 'bright_indirect',
    lightLabel: BRIGHT,
    fertilizer: '개화기 2주 1회 묽은 액체비료',
    commonPests: ['응애', '진딧물', '뿌리썩음병'],
    toxicToPets: false,
    toxicityNote: '알려진 독성은 없어요. 다만 많이 씹어 먹으면 배탈이 날 수 있어요.',
    difficulty: 'beginner',
    traits: ['flowering'],
    note: '씨앗 꼬투리를 건드리면 톡 터지며 씨가 튀어요. 물이 부족하면 잎이 바로 축 처지니 흙이 마르지 않게 신경 쓰세요.',
  },
  {
    names: ['란타나', '칠변화', 'lantana', 'lantana camara'],
    displayName: '란타나',
    scientificName: 'Lantana camara',
    wateringDays: '5-7일 (겉흙 마른 후)',
    tempRange: '15-30°C',
    humidity: '40-60%',
    light: 'direct_sun',
    lightLabel: DIRECT,
    fertilizer: '생장기 월 1회 묽은 액체비료',
    commonPests: ['진딧물', '가루이', '응애'],
    toxicToPets: true,
    toxicityNote: '특히 덜 익은 초록색 열매에 트리터페노이드 독성이 있어 구토·설사, 심하면 간 손상까지 일으켜요. 열매가 열리면 바로 치워주세요.',
    difficulty: 'beginner',
    traits: ['flowering', 'low_maintenance'],
    note: '한 꽃송이 안에서도 색이 계속 바뀐다고 칠변화라 불려요. 강한 볕과 더위를 잘 견디고 가뭄에도 강합니다.',
  },
];

/**
 * 별칭 기반 조회. 사용자는 '몬스테라 키우는 법'처럼 문장째로 넣기도 하므로
 * 완전일치 → 양방향 부분일치 순으로 넓혀서 찾는다.
 * (부분일치를 먼저 하면 '고무나무'가 '떡갈고무나무'를 가로채는 문제가 생긴다)
 */
export function findPlant(name: string): PlantRecord | null {
  const query = typeof name === 'string' ? name.trim().toLowerCase() : '';
  if (!query) return null;

  for (const plant of PLANTS) {
    for (const alias of plant.names) {
      if (alias.toLowerCase() === query) return plant;
    }
  }

  for (const plant of PLANTS) {
    for (const alias of plant.names) {
      const lowered = alias.toLowerCase();
      // 별칭이 질의에 포함되는 방향은 1글자 별칭이 오탐을 만들기 쉬워 길이를 제한한다.
      if (lowered.includes(query) || (lowered.length >= 2 && query.includes(lowered))) {
        return plant;
      }
    }
  }

  return null;
}
